### ISSUE TITLE
Scion-web should create endhost folder

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#1]
While generating the topology and configuration files of the infrastructure elements, scion-web should also additionally create an endhost folder with relevant elements in it. This folder will be automatically deployed on every SCION node.

**Comment by FR4NK-W** [comment]
Committed change to generate a endhost folder for each AS.
So commit 985865c should close this issue.

I still don't see why this folder needs to be deployed on _every_ SCION node, as opposed to only deploying it to SCION nodes that run a proxy, reverse proxy or whatever other endhost service.

**Comment by FR4NK-W** [comment]
Closing as change to local gen generator satisfies feature request
