### ISSUE TITLE
Default port values in the UI

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#13]
In the management UI, the default port values for servers should be 30041. For the BRs, this value should be 30042

**Comment by kormat** [comment]
There's no need for a static default port value. It just has to be free. And `30042` is currently reserved for libfilter.

**Comment by ercanucan** [comment]
This is aimed to give the users of the UI an idea about which port number the can use. Mainly as a guidance. Otherwise, they may have no idea which value to enter there.
As for 30042, we have been running the version 2b12c95aa4fbdd4bb9ea7583b2f0123d0fff3ba0 with BRs on 30042. Should we rather choose another "guide value" then?

**Comment by kormat** [comment]
They can use any free port number they want, is my point. So i would suggest finding a free port, and pre-filling the entry with that. And `30042` is definitely wrong in any case.

**Comment by ercanucan** [comment]
At this stage of the topology file creation we do not yet access the machines, so we don't know in advance which port numbers are free. We could access the machines to do this, but not sure if it's worth the effort. I just think it's useful to give some guide values because the system is already complex, the users may not be well trained engineers.

**Comment by ercanucan** [comment]
Just talked to @kormat about this. We concluded that we can pick another range which will not clash with any other ports used by other applications. We decided we could use 310xx range.

So let's do 31041 and 31042 respectively.

**Comment by kormat** [comment]
There's no reason to have different defaults for router vs non-router

**Comment by kormat** [comment]
Also i'd suggest just using 31000 as the default.

**Comment by FR4NK-W** [comment]
Yes 31000 might be nicer as [31000-31019 is Unassigned](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=31000)

**Comment by ercanucan** [comment]
sounds good to me.
