### ISSUE TITLE
Border Routers should not generate more than 2 log files

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-web#141]
There is a parameter that the border router accepts in its command line `log.count` that specifies the number of old log files kept. 
Modify `scion-web` so we write it in the `supervisord.conf` file for the border routers.

**Comment by matzf** [comment]
Please also adapt this in netsec-ethz/scionlab [(local_config_util.py:78)](https://github.com/netsec-ethz/scionlab/blob/12c5144bd3101961f98cca6105eacc456c660908/scionlab/util/local_config_util.py#L78).
