### ISSUE TITLE
Please keep sub/web updated in the scion repo

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion-web#44]
If the scion repo's sub/web submodule isn't kept up to date with scion-web/master, it becomes a maintenance problem. Example:

The scion repo's submodule is pointing to 2bbd92731e0bdea2cf5f27ed02c35a8a8b2423c3, which is now 7 commits behind HEAD. I can't update scion to use HEAD, as i have no way of knowing if the other 6 commits break anything, which is blocking turning on pip pinning for scion-web.

**Comment by ercanucan** [comment]
@kormat can we close this issue now? Should be addressed by 735c998b9f12c662ff2eba89ac6233cfe8e71ce0
