### ISSUE TITLE
scion-web UI does not allow inputting multiple border routers on the same machine

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#45]
The user interface throws an error when inputting multiple border router entries (with different ports) on the same machine.
It seems like the unique constraint in the database schema consider only the IP address, whereas it should be IP, port combination.

**Comment by kormat** [comment]
That depends on the overlay being used. If the overlay is UDP/IP, then yes, that is correct. If the overlay is just IP, then the existing constraint is correct.

**Comment by ercanucan** [comment]
Fixed by https://github.com/netsec-ethz/scion-web/pull/56
