### ISSUE TITLE
Hostfile generation needs to support multiple services on the same IP

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#47]
scion-web's Ansible hostfile generation variables need to be updated so that they can accommodate more than one service (e.g. border router) on the same IP.
A suggestion is the following: Running two border routers br1-1-2 and br1-1-4 on host 193.247.172.138

[border_routers]
193.247.172.138 vals='[{"br":"2", "isd":"1", "as":"1", "to_isd":"1", "to_as":"2"}, {"br":"4", "isd":"1", "as":"1", "to_isd":"2", "to_as":"21"}]' #br1-1-2 & br1-1-4

**Comment by ercanucan** [comment]
@kormat would be happy to see what you think

**Comment by kormat** [comment]
Yeah that works.

**Comment by ercanucan** [comment]
Fixed by https://github.com/netsec-ethz/scion-web/pull/56
