### ISSUE TITLE
Remove unused 2FA related code

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#48]
We have some incomplete and unused code in scion-web, regarding two factor authentication mechanisms. As we are not planning to use this feature, I suggest cleaning it up and reducing the clutter.

**Comment by matzf** [comment]
I've removed the 2FA code and then done some much more aggressive cleaning of the unused coordinator-interaction-functionality. It seems to work, as we've decided to abandon scion-web, I'm not investing the time to get this into a mergable state.
[branch:matzf/cleanup-del-coordinator-link](https://github.com/matzf/scion-web/tree/cleanup-del-coordinator-link)
