### ISSUE TITLE
Support to specify custom SSH ports for Ansible hostfile generation

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#51]
By default, Ansible uses port 22 for deploying code and configuration on the machines. As some of our contributors prefer not to use the default port for SSH in the future, it will be useful to have a mechanism to specify custom SSH ports for desired hosts in the AS configuration page, which will be then inserted automatically into the Ansible hostfile for that AS.

**Comment by klausman** [comment]
I think a better approach is to solve this on the SSH side. Since Ansible is not the only thing log into those machines. Therefore, the best approach is probably something like this in `.ssh/config` for ansible (and personal accounts):

```
Host 1.2.3.4 some.host.name.com
        User scion
        Port 24801
```

**Comment by ercanucan** [comment]
@klausman Thanks for your input! Yes, indeed, solving this on the SSH side is a better approach. I have tried this with one of our machines and it works well. Thanks!
