### ISSUE TITLE
scion-web should invoke Ansible deployment

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#7]
Currently we create the topology using scion-web and invoke ansible to do the auto-deployment from a separate console.
We can integrate this step into scion-web so that it can become the unified source to manage and deploy the ASes.

**Comment by kormat** [comment]
There's two reasons not to do this directly. The first is that the ability to run ansible is means that user effectively has root on all the machines. This is far too much power to give a web app. The second is that the ansible roles should be applied regularly/frequently, to detect/repair any problems with the deployment. This shouldn't depend on scion-web running. The simplest way to do this is to have ansible run by a cronjob.

An alternative is to have scion-web signal to something else that ansible should be run now.

**Comment by ercanucan** [comment]
For ease of use, it would be good if scion-web can take a playbook and a host file, and when clicked on "deploy", it would fire up the terminal and execute the operation with --verbose mode. This would make the interface more user-friendly.

**Comment by kormat** [comment]
@ercanucan - this is both not feasible, and still a massive security hole.

**Comment by ercanucan** [comment]
@FR4NK-W was actually able to fire up a terminal to execute commands, but as per our discussion I get the point about the security issues. As it's not a super-important feature, we can leave it.

**Comment by FR4NK-W** [comment]
branch [ansible-cli](https://github.com/netsec-ethz/scion-web/tree/ansible-cli) provides this.
Please don't merge it into master, given the security implications.
