### ISSUE TITLE
Supervisor configuration to start scionds

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-web#80]
scion-web needs to generate supervisor configuration to start sciond instances in the infrastructure.

There are two potential ways:
1) start a sciond instance on each host of the AS (probably excluding the routers),
2) extend the existing UI to choose which hosts the sciond instances should be started on.

**Comment by ercanucan** [comment]
@kormat @shitz would be happy to hear your opinion on this

**Comment by shitz** [comment]
For the simplified setup I would definitely suggest starting a sciond instance per host except if it's a BR-only host. Even though the infrastructure elements are not using sciond for path lookups yet, I think the plan is to make them do that in the future.

You could add a configuration option in the advanced setup, but this is not super critical imho.

**Comment by matzf** [comment]
This issue appears to have been addressed in #116.
